version: '3'
services:
  api:
    container_name: api_container
    image: node:14
    working_dir: /usr/src/clean-node-api
    restart: always
    command: bash -c "npm install --only=prod && npm start"
    environment:
      - PORT=5050
      - MONGO_URL=mongodb+srv://brunostel:784539126@cluster0.d0no9.mongodb.net/myFirstDatabase?retryWrites=true&w=majority
      - JWT_SECRET_KEY="secret_key"

    volumes:
      - ./dist/:/usr/src/clean-node-api/dist/
      - ./package.json:/usr/src/clean-node-api/package.json
    ports:
      - '5050:5050'
